### ISSUE TITLE
Optionen zum Ändern des aktiven Accordions [feature request]

### ISSUE THREAD

**Issue by dariorieke** [ma-zou/collapser#1]
Wäre super wenn man per JS direkt über den Collapser Accordions öffnen und schließen könnte, zB so: 
`collapser.open(3)` » öffnet das 3. (oder 2., wenn man bei 0 zu zählen anfängt) Accordion
oder `collapser.close()` » schließt alle offenen Accordions

**Comment by ma-zou** [comment]
Fixed in 430b860 new methods were added.
